services:
  wordpress:
    image: wordpress:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wordpress_dev
    ports:
      - "3002:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./docker-files/wp-config.php:/var/www/html/wp-config.php
      - ./wp-content/plugins/:/var/www/html/wp-content/plugins/
      - ./wp-content/themes/:/var/www/html/wp-content/themes/
   depends_on:
      - db
   restart: unless-stopped

  db:
    image: mariadb:latest
    container_name: wordpress_dev_db
    environment:
      MARIADB_ROOT_PASSWORD: somerootpassword
      MARIADB_DATABASE: exampledb
      MARIADB_USER: exampleuser
      MARIADB_PASSWORD: examplepass
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_CONFIG_EXTRA: |
          define( 'WP_ENVIRONMENT_TYPE', 'local' );
          define( 'WP_MEMORY_LIMIT', '512M' );
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  db_data:
