services:
  wordpress:
    image: wordpress:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wordpress_dev
    hostname: localhost
    ports:
      - "3002:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_EXTRA_CONFIG: |
        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', true);
        define('WP_DATE_FORMAT', 'd.m.Y');
        define('WP_DEFAULT_EMAIL', 'admin@example.com');
        define('WP_MULTISITE', true);
        define('WP_LANG', 'en_US');
        define('WP_TIMEZONE', 'UTC+4');
    volumes:
      - ./_dist/:/var/www/html/_dist/
      - ./docker-files/wp-config.php:/var/www/html/wp-config.php
      - ./wp-content/plugins/:/var/www/html/wp-content/plugins/
      - ./wp-content/themes/:/var/www/html/wp-content/themes/
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:lts
    container_name: wordpress_dev_db
    environment:
      MARIADB_ROOT_PASSWORD: somerootpassword
      MARIADB_DATABASE: exampledb
      MARIADB_USER: exampleuser
      MARIADB_PASSWORD: examplepass
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  db_data:
