services:
  wordpress:
    image: wordpress:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wordpress_dev
    hostname: localhost
    ports:
      - "3002:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./_dist/:/var/www/html/_dist/
      - ./docker-files/wp-config.php:/var/www/html/wp-config.php
      - ./wordpress/:/var/www/html/
      - ./wp-content/plugins/:/var/www/html/wp-content/plugins/
      - ./wp-content/themes/:/var/www/html/wp-content/themes/
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:lts
    container_name: wordpress_dev_db
    environment:
      MARIADB_ROOT_PASSWORD: somerootpassword
      MARIADB_DATABASE: exampledb
      MARIADB_USER: exampleuser
      MARIADB_PASSWORD: examplepass
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_CONFIG_EXTRA: |
          define( 'WP_ENVIRONMENT_TYPE', 'local' );
          define('ALTERNATE_WP_CRON', true);
          define( 'WP_MEMORY_LIMIT', '512M' );
          define('WP_CACHE', true);
          define('WP_SITE_TITLE', 'WP Localdev');
          define('WP_SITE_DESCRIPTION', '');
          define('WP_ADMIN_EMAIL', 'admin@example.com');
          define('WP_HOME', 'http://localhost:3002');
          define('WP_SITEURL', 'http://localhost:3002');
          define('WP_TIMEZONE', 'UTC+2');
          define('WP_TIME_FORMAT', 'H:i');
          define('WP_DATE_FORMAT', 'j F Y');
          define('WP_WEEK_STARTS_ON', 'Monday');
          define('WP_DEFAULT_USER_ROLE', 'Editor');
          define('WP_DEFAULT_THEME', 'twentytwentyfour');
          define('WP_DEFAULT_COMMENT_STATUS', 'Closed');
          define('WP_PERMALINK_STRUCTURE', '/%postname%/');
          define('WP_POST_REVISIONS', 3);
          define('WP_MULTISITE', true);
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  db_data:
